import pandas as pd
import datetime

class ReportGenerator:
    @staticmethod
    def generate_latex_report(df, dataset_name="Dataset", target_col=None, ai_score=None, ai_metric=None):
        """
        Generates a comprehensive LaTeX source code string for the final Data Science Report.
        Includes mathematical formulations used in the AI pipeline.
        """
        
        total_rows, total_cols = df.shape
        missing_vals = df.isnull().sum().sum()
        
        # Column summary for the table
        cols_summary = ""
        for col in df.columns:
            dtype = str(df[col].dtype).replace("_", "\\_")
            unique = df[col].nunique()
            nulls = df[col].isnull().sum()
            safe_col = col.replace("_", "\\_")
            cols_summary += f"            {safe_col} & {dtype} & {unique} & {nulls} \\\\\n            \\hline\n"

        latex_code = f"""\\documentclass[12pt,a4paper]{{article}}
\\usepackage[utf8]{{inputenc}}
\\usepackage{{amsmath}}
\\usepackage{{amsfonts}}
\\usepackage{{amssymb}}
\\usepackage{{graphicx}}
\\usepackage{{geometry}}
\\usepackage{{booktabs}}
\\usepackage{{hyperref}}
\\usepackage{{xcolor}}

\\geometry{{margin=1in}}

\\title{{\\textbf{{EZClean Automated AI \\& Data Science Report}}}}
\\author{{Generated by EZClean System}}
\\date{{{datetime.datetime.now().strftime('%B %d, %Y')}}}

\\begin{{document}}

\\maketitle

\\begin{{abstract}}
This report outlines the automated data ingestion, cleaning, profiling, and AI modeling steps executed by the EZClean framework on the provided \\textbf{{{dataset_name}}}. The mathematical formulations for quality indices and final machine learning benchmarks are also documented.
\\end{{abstract}}

\\section{{Dataset Profiling}}
The dataset was automatically parsed and optimized. The initial dimensions observed were:
\\begin{{itemize}}
    \\item \\textbf{{Total Rows:}} {total_rows}
    \\item \\textbf{{Total Columns:}} {total_cols}
    \\item \\textbf{{Total Missing Values Remaining:}} {missing_vals}
\\end{{itemize}}

\\subsection{{Column Diagnostics}}
\\begin{{table}}[h!]
    \\centering
    \\begin{{tabular}}{{|l|l|c|c|}}
        \\hline
        \\textbf{{Feature Name}} & \\textbf{{Data Type}} & \\textbf{{Unique Values}} & \\textbf{{Missing}} \\\\
        \\hline
{cols_summary}    \\end{{tabular}}
    \\caption{{Summary of processed dataset features.}}
\\end{{table}}

\\section{{Mathematical Formulations: Data Quality Index}}
To compute the \textit{{EZ\\_Quality\\_Index}}, a non-linear activation function was applied over the standardized linear combination of numerical features. Let $X_i$ represent the $i$-th numerical feature vector normalized to the $[-1, 1]$ range. The raw composite score $z$ for a record is given by:

\\begin{{equation}}
    z = \\sum_{{i=1}}^{{n}} X_i
\\end{{equation}}

We then applied the Sigmoid activation function to constrain the final index to a interpretable probability-like bound $(0, 1)$:

\\begin{{equation}}
    f(z) = \\frac{{1}}{{1 + e^{{-z}}}}
\\end{{equation}}

This mathematically ensures that extreme outlier combinations are squashed gracefully, providing a robust score robust against infinite skew.

"""
        if target_col and ai_score is not None:
            safe_target = target_col.replace("_", "\\_")
            latex_code += f"""
\\section{{Auto-ML Predictive Modeling}}
The EZClean AI Pipeline automatically configured and trained a Random Forest ensemble model to predict the target variable \\textbf{{{safe_target}}}. Missing categorical values were imputed, encoded, and integrated into the feature space.

\\subsection{{Model Performance}}
The model achieved the following performance on a standard 80/20 cross-validation holdout set:
\\begin{{itemize}}
    \\item \\textbf{{Primary Evaluation Metric:}} {ai_metric}
    \\item \\textbf{{Score Achieved:}} {ai_score:.4f}
\\end{{itemize}}
"""
        
        latex_code += """
\\section{{Conclusion}}
The data has been comprehensively mapped, cleaned (via IQR bounds and median/mode imputation strategies), properly scaled/encoded, and passed through our ML training workflow successfully. It is ready for production deployments.

\\end{document}
"""
        return latex_code
